import * as fs from "node:fs";
import * as path from "node:path";
import { toFixed } from "./index.js";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const mimeType = require("mime-types");
const sizeOf = require("image-size");

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const themePath = path.resolve(__dirname, "../../assets/theme");
const imgExts = [".jpg", ".jpeg", ".png", ".gif", ".webp"];

interface ThemeImage {
	width: number;
	height: number;
	data: string;
}

interface Theme {
	[key: string]: ThemeImage;
}

interface ThemeList {
	[key: string]: Theme;
}

export const themeList: ThemeList = {};

fs.readdirSync(themePath).forEach((theme) => {
	const currentThemePath = path.resolve(themePath, theme);
	if (!fs.statSync(currentThemePath).isDirectory()) return;

	if (!(theme in themeList)) themeList[theme] = {};
	const imgList = fs.readdirSync(currentThemePath);
	imgList.forEach((img) => {
		if (!imgExts.includes(path.extname(img).toLowerCase())) return;

		const imgPath = path.resolve(currentThemePath, img);
		const char = path.parse(img).name;
		const dimensions = sizeOf(imgPath);

		if (!themeList[theme]) themeList[theme] = {};
		themeList[theme][char] = {
			width: dimensions.width || 0,
			height: dimensions.height || 0,
			data: convertToDatauri(imgPath),
		};
	});
});

function convertToDatauri(filePath: string): string {
	const mime = mimeType.lookup(filePath);
	const base64 = fs.readFileSync(filePath).toString("base64");

	return `data:${mime};base64,${base64}`;
}

interface CountImageParams {
	count: number | string;
	theme?: string;
	padding?: number;
	prefix?: number;
	offset?: number;
	align?: "top" | "center" | "bottom";
	scale?: number;
	pixelated?: string;
	darkmode?: string;
}

export function getCountImage(params: CountImageParams): string {
	let {
		count,
		theme = "moebooru",
		padding = 7,
		prefix = -1,
		offset = 0,
		align = "top",
		scale = 1,
		pixelated = "1",
		darkmode = "auto",
	} = params;

	if (!(theme in themeList)) theme = "moebooru";
	padding = parseInt(String(Number(padding)), 10);
	offset = parseFloat(String(Number(offset)));
	scale = parseFloat(String(Number(scale)));

	const countArray = count.toString().padStart(padding, "0").split("");

	if (prefix >= 0) {
		countArray.unshift(...String(prefix).split(""));
	}

	if (themeList[theme]?.["_start"]) {
		countArray.unshift("_start");
	}
	if (themeList[theme]?.["_end"]) {
		countArray.push("_end");
	}

	const uniqueChar = [...new Set(countArray)];

	let x = 0,
		y = 0;

	const defs = uniqueChar.reduce((ret, cur) => {
		const themeData = themeList[theme]?.[cur];
		if (!themeData) return ret;
		let { width, height, data } = themeData;
		width *= scale;
		height *= scale;

		y = Math.max(y, height);

		ret = `${ret}
    <image id="${cur}" width="${toFixed(width, 5)}" height="${toFixed(height, 5)}" xlink:href="${data}" />`;

		return ret;
	}, "");

	const parts = countArray.reduce((ret, cur) => {
		const themeData = themeList[theme]?.[cur];
		if (!themeData) return ret;
		let { width, height } = themeData;
		width *= scale;
		height *= scale;

		let yOffset = 0;

		if (align === "center") {
			yOffset = (y - height) / 2;
		} else if (align === "bottom") {
			yOffset = y - height;
		}

		const image = `${ret}
    <use x="${toFixed(x, 5)}"${yOffset ? ` y="${toFixed(yOffset, 5)}"` : ""} xlink:href="#${cur}" />`;

		x += width + offset;

		return image;
	}, "");

	x -= offset;

	const style = `
  svg {
    ${pixelated === "1" ? "image-rendering: pixelated;" : ""}
    ${darkmode === "1" ? "filter: brightness(.6);" : ""}
  }
  ${darkmode === "auto" ? `@media (prefers-color-scheme: dark) { svg { filter: brightness(.6); } }` : ""}
  `;

	return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by https://github.com/mikndotdev/BetterMoeCounter -->
<svg viewBox="0 0 ${toFixed(x, 5)} ${toFixed(y, 5)}" width="${toFixed(x, 5)}" height="${toFixed(y, 5)}" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <title>Moe Counter!</title>
  <style>${style}</style>
  <defs>${defs}
  </defs>
  <g>${parts}
  </g>
</svg>
`;
}
